// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Lj2X6yDUJDzdwSyuvr8c-Qh5jYsMA4M',
    appId: '1:489761858597:web:975013d32867d8d4f78bcc',
    messagingSenderId: '489761858597',
    projectId: 'sfi-equipment-tracker',
    authDomain: 'sfi-equipment-tracker.firebaseapp.com',
    storageBucket: 'sfi-equipment-tracker.appspot.com',
    measurementId: 'G-Y586M5GHY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjvh-IQzCsmIRYQREhlOwyYLbrNRR0UOg',
    appId: '1:489761858597:android:79ad41a0e0d67accf78bcc',
    messagingSenderId: '489761858597',
    projectId: 'sfi-equipment-tracker',
    storageBucket: 'sfi-equipment-tracker.appspot.com',
  );
}
